apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-application-prop
data:
  application.properties: |
    {{ .Files.Get "config/application.properties" | nindent 4 }}
